# variables:
  # ADOUrl: defined on azure portal

trigger:
  batch: true
  branches:
    include:
    - v3
    - v3-release
    - dev
    - main

variables:
  NugetSecurityAnalysisWarningLevel: none
  
jobs:
- job: 'Sync_GitHub_To_AzureDevOps'
  pool: 
    vmImage: 'windows-latest'
  steps:
  - task: Powershell@2
    displayName: sync from GitHub to Azure DevOps
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      targetType: inline
      script: |
        Function Sync([string]$branch) {
          git fetch $(Build.Repository.Uri) $branch
          git checkout FETCH_HEAD
          git checkout -b $branch
          $B64_PAT=[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("user:$(System.AccessToken)"))
          git -c http.extraHeader="Authorization: Basic $B64_PAT" push $(ADOUrl) $branch -uf
        }

        git init
        Sync("$(Build.SourceBranch)")
        popd