# variables:
  # ADOUrl: defined on azure portal

trigger:
  batch: true
  branches:
    include:
    - v3
    - v3-release
    - dev
    - main
pr: none

variables:
  NugetSecurityAnalysisWarningLevel: none
  
jobs:
- job: 'Sync_GitHub_To_AzureDevOps'
  pool: 
    vmImage: 'windows-latest'
  steps:
  - task: Powershell@2
    displayName: Sync from GitHub to Azure DevOps
    inputs:
      targetType: inline
      script: |
        $B64_PAT=[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("user:$(System.AccessToken)"))
        git -c http.extraHeader="Authorization: Basic $B64_PAT" push $(ADOUrl) HEAD:$(Build.SourceBranch) -f
